<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
/** @var $viewModelCartStockThreshold \Sg\CartStockThreshold\ViewModel\ViewModelCartStockThreshold */
$viewModelCartStockThreshold = $block->getData('viewModelCartStockThreshold');
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <div><?=var_dump($viewModelCartStockThreshold->test());?></div>
                <button data-bind="scope: 'addtocartthreshold'" type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart <?= $viewModelCartStockThreshold->isAddToCartBtnEnabled($_product) ? '' : 'disabled';?>"
                        id="product-addtocart-button" disabled
                        data-bind="attr: {
            class: getEnabled().class
        }">
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script type="text/x-magento-init">
    {
        "#product-addtocart-button": {
            "Magento_Ui/js/core/app": {
            	"components": {
                	"addtocartthreshold": {
                    	"component": "Sg_CartStockThreshold/js/catalog-add-to-cart/stock-disable"
                	}
            	}
        	}
        }
    }
</script>
